name: Cypress Tests with Dependency and Artifact Caching

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome

      - name: Upload Cypress report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/results/*.html
